const admin = require('firebase-admin');
const serviceAccount = require('../seconde-b47a6-firebase-adminsdk-fbsvc-26728f2671.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

async function retriggerEmbeddings() {
  // Get recent articles
  const snapshot = await db.collection('articles')
    .orderBy('createdAt', 'desc')
    .limit(5)
    .get();
  
  console.log(`Found ${snapshot.docs.length} articles to retrigger`);
  
  for (const doc of snapshot.docs) {
    const data = doc.data();
    console.log(`Retriggering: ${doc.id} - ${data.title}`);
    
    // Update a field to trigger the Firestore listener
    await doc.ref.update({
      embeddingRetriggeredAt: admin.firestore.FieldValue.serverTimestamp()
    });
  }
  
  console.log('Done! Embeddings will be generated by the trigger.');
}

retriggerEmbeddings().then(() => process.exit(0));
