export interface UserPreferences {
  sizes: string[];
  favoriteBrands: string[];
  location?: {
    latitude: number;
    longitude: number;
    city: string;
  };
  shippingCarriers?: string[];
  notifications?: {
    email: boolean;
    push: boolean;
    newMessages: boolean;
    newOrders: boolean;
    priceDrops: boolean;
    articleFavorited: boolean;    // Quand quelqu'un ajoute mon article en favori
    swapZoneReminder: boolean;    // Rappel 3 jours avant une swap zone
    offerReceived: boolean;       // Nouvelle proposition d'achat
    offerResponse: boolean;       // Réponse à ma proposition
  };
  privacy?: {
    showProfilePhoto: boolean;
    /** @deprecated Not implemented — toggle removed from UI */
    allowSearchEngines?: boolean;
  };
}

/**
 * AI-generated style profile from user behavior
 * Generated by Gemini after signup with guest data
 */
export interface StyleProfile {
  styleTags: string[];                // ["Streetwear", "Vintage", "Casual"]
  styleDescription: string;           // Description naturelle du style en français
  recommendedBrands: string[];        // Marques suggérées
  suggestedSizes: { top: string; bottom: string };
  confidence: number;                 // 0-1 score de confiance
  generatedAt: Date;
}

export interface User {
  id: string;
  email: string;
  displayName?: string;
  bio?: string;
  profileImage?: string;
  createdAt: Date;
  rating?: number;
  phoneNumber?: string;
  address?: {
    street: string;
    city: string;
    province?: string;
    postalCode: string;
    country: string;
  };
  isActive?: boolean;
  accountType?: 'user' | 'shop';
  isAdmin?: boolean;
  preferences?: UserPreferences;
  styleProfile?: StyleProfile;
  onboardingCompleted?: boolean;
  authProvider?: 'email' | 'google' | 'apple';
  fcmTokens?: string[];  // Firebase Cloud Messaging tokens for push notifications
  likedSellers?: string[];     // IDs des vendeurs aimés
  sellerLikesCount?: number;   // Nombre de likes reçus en tant que vendeur
  articlesCount?: number;      // Nombre d'articles actifs
  salesCount?: number;         // Nombre de ventes réalisées
  // Stripe Connect
  stripeAccountId?: string;
  stripeAccountStatus?: string;
  stripeChargesEnabled?: boolean;
  stripePayoutsEnabled?: boolean;
  stripeDetailsSubmitted?: boolean;
}

export interface ArticleImage {
  url: string;
  blurhash?: string;
}

export interface ArticleDimensions {
  length: number; // cm
  width: number; // cm
  height: number; // cm
}

/** Sizing system. Single source of truth — data/sizes.ts re-exports this. */
export type SizeSystem = 'US' | 'EU';

/**
 * Article size, carrying its sizing system so US/EU values never collide.
 * Stored on the article and copied verbatim into swaps.
 */
export interface ArticleSize {
  value: string;
  system: SizeSystem;
}

export interface Article {
  id: string;
  title: string;
  description: string;
  price: number;
  images: ArticleImage[];
  /** @deprecated Use categoryIds instead */
  category: string;
  categoryIds: string[]; // IDs hiérarchiques ex: ['home', 'home_decoration', 'home_decoration_vases']
  size?: ArticleSize | null;
  brand?: string;
  color?: string;
  colors?: string[];
  material?: string;
  materials?: string[];
  pattern?: string;
  condition: 'neuf' | 'très bon état' | 'bon état' | 'satisfaisant';
  sellerId: string;
  sellerName: string;
  sellerImage?: string;
  createdAt: Date;
  isActive: boolean;
  isSold: boolean;
  likes: number;
  views: number;
  location?: string; // Ville ou code postal (legacy)
  neighborhood?: MeetupNeighborhood; // Quartier pour meetup
  neighborhoods?: MeetupNeighborhood[]; // Quartiers multiples pour meetup
  preferredMeetupSpots?: MeetupSpot[]; // Lieux de rencontre préférés du vendeur
  weight?: number; // Poids en kg
  dimensions?: ArticleDimensions; // Dimensions calculées automatiquement selon catégorie
  isHandDelivery?: boolean;
  isShipping?: boolean;
  packageSize?: 'small' | 'medium' | 'large';
  // Price drop tracking
  originalPrice?: number;         // Prix avant la premiere baisse
  lastPriceDropAt?: Date;         // Date de la derniere baisse
  priceDropPercent?: number;      // Pourcentage de reduction
  promotionActive?: boolean;      // Promo activee manuellement par le vendeur
}

// Extended Article with location data used in search results
export interface ArticleWithLocation extends Omit<Article, 'location'> {
  location?: {
    lat: number;
    lon: number;
    distance?: number; // in km
    address?: string;
  };
}

export type MessageType = 'text' | 'image' | 'offer' | 'system';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read';
// Legacy offer status (kept for backward compatibility)
export type LegacyOfferStatus = 'pending' | 'accepted' | 'rejected';

// New offer status with counter-offer support
export type OfferStatus =
  | 'pending'           // En attente de réponse
  | 'accepted'          // Acceptée → paiement
  | 'rejected'          // Refusée définitivement
  | 'completed'         // Transaction terminée (meetup complété)
  | 'counter_price'     // Contre-offre sur le prix
  | 'counter_location'  // Contre-proposition de lieu
  | 'counter_time'      // Contre-proposition d'horaire
  | 'expired';          // Expirée (après 48h)

export interface ShippingAddress {
  name: string;
  street: string;
  city: string;
  province: string;
  postalCode: string;
  country: string;
  phoneNumber?: string;
}

/** Shipping estimate attached to chat offers (legacy field structure). */
export interface ShippingEstimate {
  carrier: string;
  serviceName: string;
  estimatedDays: string;
  amount: number;
  currency: string;
  /** @deprecated Legacy Intelcom field, kept for existing Firestore documents. */
  intelcomRateId?: string;
  /** @deprecated Legacy Intelcom field, kept for existing Firestore documents. */
  intelcomServiceLevel?: string;
}

export interface MessageOffer {
  amount: number;
  status: OfferStatus;
  message?: string;
  shippingAddress?: ShippingAddress;
  shippingEstimate?: ShippingEstimate;
  totalAmount?: number; // amount + shipping
}

export interface MessageImage {
  url: string;
  width?: number;
  height?: number;
  thumbnail?: string;
}

export interface Message {
  id: string;
  chatId: string;
  senderId: string;
  receiverId: string;
  type: MessageType;
  content: string;
  timestamp: Date;
  status: MessageStatus;
  isRead: boolean;
  // Optional metadata based on message type
  offer?: MessageOffer;
  image?: MessageImage;
}

export interface ChatParticipant {
  userId: string;
  userName: string;
  userImage?: string;
  /** Backend trigger uses profileImage for map-format participantsInfo */
  profileImage?: string;
}

export interface Chat {
  id: string;
  participants: string[];
  participantsInfo: ChatParticipant[];
  sellerId?: string;
  articleId?: string;
  articleTitle?: string;
  articleImage?: string;
  articlePrice?: number;
  lastMessage?: string;
  lastMessageType?: MessageType;
  lastMessageTimestamp?: Date;
  unreadCount: { [userId: string]: number };
  createdAt: Date;
  updatedAt: Date;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  subcategories?: string[];
}

export type TransactionDeliveryType = 'meetup' | 'shipping';

export type TransactionStatus =
  | 'pending_payment'    // Awaiting Stripe payment (shipping only)
  | 'meetup_pending'     // Meetup requested, awaiting seller confirmation
  | 'meetup_confirmed'   // Seller confirmed meetup
  | 'meetup_completed'   // Both parties confirmed exchange
  | 'paid'               // Payment received (shipping) — seller prepares parcel
  | 'label_created'      // Shipping label purchased, before first carrier scan
  | 'shipped'            // Package shipped (in transit)
  | 'delivered'          // Package delivered — funds held during dispute window
  | 'completed'          // Sale finalized after 7-day dispute window
  | 'delivery_failed'    // Carrier delivery failed — dispute opened, funds frozen
  | 'lost'               // Parcel declared lost — funds frozen
  | 'cancelled'          // Cancelled by either party
  | 'disputed'           // Dispute opened on the order
  | 'refund_in_progress' // Transient — resolves to 'refunded'
  | 'refunded';          // Refund completed

export interface Transaction {
  id: string;
  articleId: string;
  buyerId: string;
  sellerId: string;
  amount: number;
  shippingCost: number;
  totalAmount: number;
  deliveryType: TransactionDeliveryType;
  status: TransactionStatus;
  // Service fee (commission Seconde)
  serviceFee?: number;
  serviceFeePercent?: number;
  sellerPayout?: number;
  // Stripe payment
  stripePaymentIntentId?: string;
  stripeClientSecret?: string;
  stripeChargeId?: string;
  // ShipEngine shipping
  shipEngineRateId?: string;
  shipEngineLabelId?: string;
  carrierCode?: string;
  shippingLabelUrl?: string;
  trackingNumber?: string;
  trackingStatus?: string;
  trackingUrl?: string;
  shippingAddress?: ShippingAddress;
  // Legacy Intelcom (kept for migration)
  intelcomBookingId?: string;
  // Meetup details
  meetupSpot?: MeetupSpot;
  meetupConfirmedAt?: Date;
  meetupCompletedAt?: Date;
  // Chat reference
  chatId?: string;
  // Timestamps
  createdAt: Date;
  paidAt?: Date;
  shippedAt?: Date;
  deliveredAt?: Date;
}

export type SortBy = 'recent' | 'price_asc' | 'price_desc' | 'popular';

export interface SearchFilters {
  category?: string; // Legacy
  categoryIds?: string[]; // Nouvelle recherche par IDs
  colors: string[];
  sizes: ArticleSize[];
  materials: string[];
  condition?: string;
  minPrice?: number;
  maxPrice?: number;
  brands?: string[];
  sortBy?: SortBy;
}

// Shop types
export type ShopType = 
  | 'friperie'
  | 'depot-vente'
  | 'vintage'
  | 'luxe-seconde-main'
  | 'streetwear'
  | 'concept-store'
  | 'createurs-designer'
  | 'workwear-militaire'
  | 'boutique-enfant'
  | 'chaussures-sneakers'
  | 'accessoires-maroquinerie'
  | 'librairie-occasion'
  | 'jouets-puericulture'
  | 'hightech-electronique'
  | 'maison-deco'
  | 'sport-outdoor'
  | 'vinyles-musique'
  | 'beaute-cosmetiques'
  | 'ressourcerie'
  | 'autre';

export const ShopTypeLabels: Record<ShopType, string> = {
  'friperie': 'Friperie',
  'depot-vente': 'Dépôt-vente',
  'vintage': 'Vintage',
  'luxe-seconde-main': 'Luxe & Seconde main',
  'streetwear': 'Streetwear',
  'concept-store': 'Concept store',
  'createurs-designer': 'Créateurs & Designer',
  'workwear-militaire': 'Workwear & Militaire',
  'boutique-enfant': 'Boutique enfant',
  'chaussures-sneakers': 'Chaussures & Sneakers',
  'accessoires-maroquinerie': 'Accessoires & Maroquinerie',
  'librairie-occasion': 'Librairie d\'occasion',
  'jouets-puericulture': 'Jouets & Puériculture',
  'hightech-electronique': 'High-tech & Électronique',
  'maison-deco': 'Maison & Déco',
  'sport-outdoor': 'Sport & Outdoor',
  'vinyles-musique': 'Vinyles & Musique',
  'beaute-cosmetiques': 'Beauté & Cosmétiques',
  'ressourcerie': 'Ressourcerie',
  'autre': 'Autre',
};

export type ShopStatus = 'pending' | 'approved' | 'rejected' | 'suspended';

export interface ShopVerificationDetails {
  reason?: string;
  verifiedAt?: Date;
  verifiedBy?: string;
}

export interface ShopLegalInfo {
  businessNumber?: string;    // NEQ (Numero d'entreprise du Quebec) ou BN/NE federal
  gstNumber?: string;         // Numero de TPS
  qstNumber?: string;         // Numero de TVQ (Quebec)
  bankTransit?: string;       // Numero de transit (5 chiffres)
  bankInstitution?: string;   // Numero d'institution (3 chiffres)
  bankAccount?: string;       // Numero de compte (7-12 chiffres)
}

export interface ShopAddress {
  street: string;
  city: string;
  postalCode: string;
  country: string;
}

export interface ShopLocation {
  latitude: number;
  longitude: number;
  geohash?: string; // For Firestore geolocation queries
}

export interface ShopSocialMedia {
  instagram?: string;
  facebook?: string;
}

export interface OpeningHours {
  [day: string]: {
    open: string;
    close: string;
  } | null;
}

export interface Shop {
  id: string;
  ownerId: string;
  name: string;
  description: string;
  type: ShopType;
  address: ShopAddress;
  location: ShopLocation;
  phoneNumber: string;
  email: string;
  website?: string;
  socialMedia?: ShopSocialMedia;
  openingHours: OpeningHours;
  logo?: string;
  images: string[];
  status: ShopStatus;
  verificationDetails?: ShopVerificationDetails;
  legalInfo?: ShopLegalInfo;
  rating?: number;
  reviewCount: number;
  articlesCount: number;
  createdAt: Date;
  updatedAt: Date;
}

// Notification types
export type NotificationType =
  | 'shop_created'
  | 'shop_approved'
  | 'shop_rejected'
  | 'new_message'
  | 'article_liked'
  | 'article_favorited'    // Quelqu'un a ajouté mon article en favori
  | 'article_sold'
  | 'price_drop'           // Baisse de prix sur un article en favori
  | 'offer_received'
  | 'offer_counter'        // Contre-offre reçue
  | 'offer_accepted'       // Offre acceptée
  | 'offer_rejected'       // Offre refusée
  | 'offer_expired'        // Offre expirée
  | 'meetup_reminder'      // Rappel de meetup (1h avant)
  | 'meetup_confirmed'     // Meetup confirmé
  | 'meetup_cancelled'     // Meetup annulé
  | 'no_show_reported'     // No-show signalé
  | 'swap_zone_reminder'   // Rappel Swap Zone (3 jours avant)
  | 'swap_proposed'
  | 'swap_accepted'
  | 'swap_declined'
  | 'swap_photos_uploaded'
  | 'swap_shipped'
  | 'swap_received'
  | 'swap_completed'
  | 'swap_party_starting'
  | 'swap_party_ending'
  | 'swap_match_found';

export interface NotificationData {
  articleId?: string;
  articleTitle?: string;
  chatId?: string;
  partyId?: string;
  partyName?: string;
  userId?: string;
  userName?: string;
  amount?: number;
  oldPrice?: number;
  newPrice?: number;
}

export interface Notification {
  id: string;
  userId: string;
  type: NotificationType;
  title: string;
  message: string;
  data?: NotificationData;
  isRead: boolean;
  createdAt: Date;
}

// ============================================
// MEETUP SYSTEM TYPES
// ============================================

// Catégories de lieux de rencontre
export type MeetupSpotCategory =
  | 'cafe'
  | 'metro'
  | 'library'
  | 'mall'
  | 'park'
  | 'community_center'
  | 'other_public';

export const MeetupSpotCategoryLabels: Record<MeetupSpotCategory, string> = {
  'cafe': 'Café',
  'metro': 'Station de métro',
  'library': 'Bibliothèque',
  'mall': 'Centre commercial',
  'park': 'Parc',
  'community_center': 'Centre communautaire',
  'other_public': 'Autre lieu public',
};

// Quartier/Zone de Montréal
export interface MeetupNeighborhood {
  id: string;
  name: string;
  borough: string; // Arrondissement
}

// Lieu de rencontre spécifique
export interface MeetupSpot {
  id?: string;
  name: string;
  category: MeetupSpotCategory;
  neighborhood: MeetupNeighborhood;
  address?: string;
  coordinates?: {
    latitude: number;
    longitude: number;
  };
  // Si c'est un lieu suggéré par la communauté
  isUserSuggested?: boolean;
  suggestedBy?: string;
}

// Historique des négociations d'offre
export type OfferHistoryAction =
  | 'created'
  | 'counter_price'
  | 'counter_location'
  | 'counter_time'
  | 'accepted'
  | 'rejected'
  | 'expired';

export interface OfferHistoryEntry {
  action: OfferHistoryAction;
  by: string; // userId
  timestamp: Date;
  previousValue?: any;
  newValue?: any;
  message?: string;
}

// Détails du meetup dans une offre
export interface MeetupDetails {
  location: MeetupSpot;
  dateTime?: Date; // Optionnel - la date/heure sera convenue via le chat
  proposedBy: 'buyer' | 'seller';
  // Pour le suivi
  confirmedAt?: Date;
  completedAt?: Date;
  noShow?: {
    reportedBy: string;
    reportedAt: Date;
    reason?: string;
  };
}

// Nouvelle structure d'offre avec meetup
export interface MeetupOffer {
  id: string;
  amount: number;
  status: OfferStatus;
  message?: string;

  // Meetup info
  meetup: MeetupDetails;

  // Historique des négociations
  history: OfferHistoryEntry[];

  // Expiration (48h par défaut)
  expiresAt: Date;

  // Métadonnées
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
  lastActionBy: string;
}

// Score de fiabilité utilisateur pour les meetups
export interface UserMeetupScore {
  userId: string;
  totalMeetups: number;
  completedMeetups: number;
  noShows: number;
  cancellations: number;
  reliabilityScore: number; // 0-100
  lastUpdated: Date;
}

// Extension de MessageOffer pour supporter le meetup
export interface MessageOfferWithMeetup {
  amount: number;
  status: OfferStatus;
  message?: string;

  // Legacy shipping (optional, pour migration)
  shippingAddress?: ShippingAddress;
  shippingEstimate?: ShippingEstimate;
  totalAmount?: number;

  // New meetup fields
  meetup?: MeetupDetails;
  history?: OfferHistoryEntry[];
  expiresAt?: Date;
  offerId?: string; // Reference to the offer document
}

// ============================================
// SWAP SYSTEM TYPES
// ============================================

// Swap Zone — single, always-active generalist zone (no time window, no theme,
// no participants). The deterministic doc is swapParties/generalist.
export interface SwapParty {
  id: string;
  name: string;
  isGeneralist?: boolean; // true = all items accepted (always true for the zone)
  itemsCount?: number;
  swapsCount?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

// Item in a Swap Party (reference to an Article)
export interface SwapPartyItem {
  id: string;
  partyId: string;
  articleId: string;
  sellerId: string;
  sellerName: string;
  sellerImage?: string;
  title: string;
  price: number; // Valeur estimée pour le swap
  imageUrl?: string;
  isSwapped: boolean;
  addedAt: Date;
}

// Extended SwapPartyItem with full Article metadata for filtering
export interface SwapPartyItemExtended extends SwapPartyItem {
  categoryIds?: string[];
  size?: ArticleSize | null;
  brand?: string;
  color?: string;
  material?: string;
  pattern?: string;
  condition?: 'neuf' | 'très bon état' | 'bon état' | 'satisfaisant';
}

// Swap status
export type SwapStatus =
  | 'proposed'         // Proposition envoyée
  | 'payment_pending'  // Acceptée avec complément — en attente du paiement Stripe
  | 'accepted'         // Acceptée (sans complément, OU après paiement du complément)
  | 'declined'         // Refusée
  | 'cancelled'        // Annulée par l'initiateur
  | 'photos_pending'   // En attente des photos
  | 'shipping'         // En cours d'envoi
  | 'completed'        // Échange terminé
  | 'disputed';        // Litige ouvert

// Swap exchange mode
export type SwapExchangeMode = 'hand_delivery' | 'shipping';

// Swap photo proof
export interface SwapPhotoProof {
  userId: string;
  photos: string[]; // URLs
  uploadedAt: Date;
  isValidated: boolean;
}

// Info for a single item in a swap (used in arrays)
export interface SwapItemInfo {
  articleId: string;
  title: string;
  price: number;
  imageUrl?: string;
  brand?: string;
  size?: ArticleSize | null;
}

// Swap - An exchange between two users (supports multi-article)
export interface Swap {
  id: string;
  partyId?: string; // Optional: if swap originated from a party

  // Initiator (person who proposed)
  initiatorId: string;
  initiatorName: string;
  initiatorImage?: string;

  // Multi-article: arrays of items on each side
  initiatorItems: SwapItemInfo[];
  receiverItems: SwapItemInfo[];
  initiatorTotalValue: number;   // Sum of initiator items prices
  receiverTotalValue: number;    // Sum of receiver items prices

  // @deprecated — kept for backward compat with old single-item swaps
  initiatorItemId?: string;
  initiatorItem?: SwapItemInfo;
  receiverItemId?: string;
  receiverItem?: SwapItemInfo;

  // Receiver (person who received proposal)
  receiverId: string;
  receiverName: string;
  receiverImage?: string;

  // Cash top-up (if any). amount is IN CENTS.
  cashTopUp?: {
    amount: number;
    payerId: string; // Who pays the difference
  };
  // Stripe payment for the cash top-up
  paymentIntentId?: string;
  topUpFee?: number; // Service fee charged on top of the top-up (cents)
  paidAt?: Date;

  // Exchange details
  exchangeMode?: SwapExchangeMode;
  status: SwapStatus;
  message?: string; // Message from initiator

  // Photo proofs
  initiatorPhotos?: SwapPhotoProof;
  receiverPhotos?: SwapPhotoProof;

  // Shipping confirmations
  initiatorShippedAt?: Date;
  receiverShippedAt?: Date;
  initiatorReceivedAt?: Date;
  receiverReceivedAt?: Date;

  // Chat reference
  chatId?: string;

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
  acceptedAt?: Date;
  completedAt?: Date;

  // Ratings
  initiatorRating?: {
    score: number;
    comment?: string;
  };
  receiverRating?: {
    score: number;
    comment?: string;
  };
}

// ============================================
// WALLET TYPES
// ============================================

export type WalletLedgerType =
  | 'sale_credit'
  | 'purchase_debit'
  | 'withdrawal'
  | 'withdrawal_failed'
  | 'refund_credit';

export interface WalletLedgerEntry {
  id: string;
  type: WalletLedgerType;
  amount: number;
  balanceAfter: number;
  description: string;
  transactionId?: string;
  createdAt: string;
}

export interface WalletInfo {
  hasWallet: boolean;
  balance: number;
  pendingBalance: number;
  status: 'active' | 'inactive';
  ledger: WalletLedgerEntry[];
}

